-- insert initial test data
-- the id is hardcode to enable references between further test data
INSERT INTO horse (ID, NAME, BREED, MIN_SPEED, MAX_SPEED, CREATED, UPDATED, DELETED )
VALUES (20,'horse1', 'Cob', 40.1, 50.0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0),
  (21,'horse2', 'Arab', 40.5, 50.7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0),
  (22,'horse3', 'Andalusian', 40.0, 60.0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0),
  (23, 'horse4', 'Dorako', 52.0, 57.0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0),
  (24, 'horse5', 'Eali', 43.5, 53.4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0);

INSERT INTO jockey (ID, NAME, SKILL, CREATED, UPDATED, DELETED )
VALUES (20,'jockey1',  40.1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),0),
    (21,'jockey2', 40.5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),0),
    (22,'jockey3', 40.0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),0),
    (23, 'jockey4', 32.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,0),
    (24, 'jockey5', 289.123, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),0);
